### ISSUE TITLE
Qt: Some way to renew domains

### ISSUE THREAD

**Issue by luke-jr** [namecoin/namecoin-legacy#131]
I don't see any way to renew domains in Namecoin-Qt. As a result, I lost a number of domains a few months ago. Please add some way to renew soon, so I can avoid losing any more. :(

Auto-renew (while the client is running of course) or even renew-in-advance would be nice too :)

**Comment by phelixbtc** [comment]
I rarely use the GUI to renew but it seems you have to select a name, click "configure name..." (will load current value) and then "ok". A "renew" button and right-click menu entry would certainly be nice. Also we should implement "name_renew" or something to do a "name_update" with the current value.

And auto-renew... yeah.

**Comment by chronokings** [comment]
sorry you lost some names luke.
To update (renew), double click a name and press ok (and enter password if encrypted).

to autorenew - maybe would need to pre-allocate the fee/tx like with the auto-firstupdate if wallet encrypted ?
you probably still need to enter password even if there is no fee (when close to expiry).

**Comment by luke-jr** [comment]
I like the idea to pre-allocate/sign a transaction in advance. Might nLockTime it to avoid premature mining.

**Comment by JeremyRand** [comment]
Yes, I agree that nLockTime is a good way to handle this; I had that idea a few months ago.  Would transaction malleability be a potential problem?

**Comment by luke-jr** [comment]
Not if you just wait until the last name_update confirms to make the new transaction.

**Comment by JeremyRand** [comment]
Right, but that makes it impossible to chain a bunch of name_update operations ahead of time.  I guess there's not much that can be done there until malleability is dealt with (which I understand is a large undertaking, but I don't know much about it).

**Comment by domob1812** [comment]
To turn the ideas here into concrete patches, please let me know your opinion on the following:

1) name_renew:  I can, of course, trivially implement this - but do we really need it?  Is it so hard to do name_update instead with the correct value?  Also note that libnmcrpc contains some CLI tools that can do that "nmupdate update NAME" in particular.  But if you think we can use name_renew, I'll prepare a patch.

2) UI: As was already mentioned, you can renew a name by "updating" (changing) it and not changing the value in the dialog.  Does everyone agree that we want some "shortcut" UI element to do this more directly for pure updates?

3) Auto-renew & time lock:  Doesn't this run a risk of the time lock being inappropriate if the block rate is not the one that was assumed while creating the tx?  I understand that there is desire for precreated transactions (especially since @JeremyRand is interested in cold storage of names), but for me, this seems like an entirely different feature than plain "auto renew" to avoid forgetting to renew the names.

4) Auto-renew by itself:  I can work on this.  Do we want it in the UI or also the daemon itself?  (Like:  Automatically renew names that have fallen below 1000 blocks expire time when the wallet is unlocked the next time.)  We could even really prepare a tx in advance for the next update and just keep it "private" (like the name_firstupdate is done in Qt) - then there's no need for time locking.  With that, it would be enough if the wallet was unlocked once in the last 36000 blocks so a update tx could have been prepared.

**Comment by luke-jr** [comment]
1) Probably not necessary.

2) At the very least, there should be some indication how to renew.

3) nLockTime can be specified as a block height, not just a time.

**Comment by domob1812** [comment]
Thanks for the feedback!  I didn't know that lock time is possible per block height, that makes sense, then.  But still, I think that such "advanced cold storage features" are not an immediate priority for Namecoin-Qt.

However, I like the idea of preparing at least one renewal transaction per name whenever the wallet is unlocked, and sending them automatically (if the user opts in to this).  What I imagine is this:

*) There's some command-line / namecoin.conf setting, autorenew=true (or autorenew=1000) to enable everything.
*) For each name, the client (daemon and Qt alike) tries to keep one renew transaction in store.  These could be stored in the wallet DB.
*) Whenever the wallet is unlocked, the client prepares renew transactions for all names that don't yet have one.
*) When a name runs close to expiry, the prepared tx is broadcasted.

This should be relatively straight-forward to implement.  A difficulty could be tx outputs that are needed to pay fees, since the prepared transactions are invalidated as soon as they are spent by some other transaction.  So we would either have to lock them (causing confusion for the user, probably) or run the risk of invalidating prepared transactions.  For now, neither is a concern, though, as updates are free when the name is aged long enough.  (I definitely know that 10k blocks until expiry are enough to get a free update; not sure about the exact number, could be calculated from priority rules.)

**Comment by n074v41l4bl34u** [comment]
The base scenario should be and automatic name renew like so:
IF 
- the client runs, and 
- the wallet is unlocked (ex. with: walletpassphrase <passphrase> <timeout> [mintonly] as in PPC, NVC clients, where [mintonly] param be changed to [updateonly] or something more applicable)

It is a good idea to specify the n number of blocks before expiry when the client starts the update process, so the full command would be something like:
walletpassphrase <passphrase> <timeout> [updateonly] [updatebeforenexpiry]

or to be more precise with the name, so the [updateonly] param can be omitted:
setautoupdate <passphrase> <timeout> [updatebeforenexpiry]

This way one does start up the client, easily set up this command and can then forget about any manual updates and the wallet is unlocked only for the purpose of auto-updates. This should be the base scenario. Any other, more advanced functionality can be build later by extending this command but this core functionality is essential for people to feel safe about their domains.

**Comment by JeremyRand** [comment]
@domob1812 , regarding transactions being invalidated by spending the change output, wouldn't that only happen while the wallet is unlocked, since the change can't be spent without unlocking the wallet?  If that's correct, just regenerate all of the name renewals whenever the user makes a transaction.

I think Armory should be adapted to Namecoin if we want to do cold storage; trying to do it with Namecoin-Qt would be a lot of extra effort with little obvious benefit.  But, in cases of a user just forgetting to renew a names, or a user having a lot of names and not wanting to manually renew all of them whenever they get near expiry, I think precreating and signing transactions would be a good solution.  Hypothetically we could let the user configure how many renewals to precreate; if the renewals are stored locally, then we can store as many as we want (e.g. 10 years of automatic renewals as long as Namecoin-Qt is open without security issues).

All that said, a softfork like Ryan, Luke, and I were discussing, so that renewals can use an "anyone can spend" script, would be a much better solution, so I'd be against expending large effort on automatic renewals when a softfork would solve it much more cleanly.

**Comment by domob1812** [comment]
Good point, I missed that even though it is somewhat obvious. :)  I definitely agree with you, that more sophisticated cold storage is desirable but nothing for the core daemon.  (This is one of the points I tried to make above.)  I also agree that a simple auto-renew is, on the other hand, a good thing to have to prevent accidental loss due to forgetting to renew.

Do you think something like I described above makes sense to implement?  Or should we use time locked transactions instead?  My understanding is that time locked transactions would be kept in the wallet and rebroadcasted as necessary before the network forgets them - but they wouldn't prevent to issue a manual name_update that double spends them.  Or would they?  In this case, it seems like a good idea to (optionally, if the user wants it) simply construct a time locked renewal transaction each time a name is changed or registered, which would also take care of the auto renew in some sense.

**Comment by phelixbtc** [comment]
my 50mNMC:
**name_renew** - not really necessary. Should somebody want to implement it maybe the <value> parameter of name_update could be optional so that we can spare the additional command.
**GUI renew Button** - important. Also helps the user to understand that renewal is necessary.
**auto-renew** - Now that I think about it this feature seems relatively complicated in comparison to the benefit. Especially with locked wallets it might lead to nontransparent behavior. What about a simple warning (balloon popup) about soon expiring domains instead? That should go a long way...

**Comment by chronokings** [comment]
this is how mikhail did the firstupdate -- not sure if this helps - maybe can be done from name_new....
"QT client sends 0.015 on name_new, then sends 0.01 from it on firstupdate (thus paying 0.005 fee directly from the locked coin). This allows easily preparing automatic firstupdate. If we pay fee from another tx-out, the user may spend it while firstupdate is still pending (non-broadcasted) and it will fail."

you could spend 1nmc on name_new, and prepare tx at the same time (when wallet unlocked) and prepare several name_updates (as well as firstupdate)?
 edit: must have read it here:
https://forum.namecoin.info/viewtopic.php?p=4496#p4496

**Comment by Tranxor** [comment]
I agree with phelixbtc,
A GUI Renew Button would be a good idea.

auto_renew not so much. Because I think a human action should always be needed.
Otherwise the big domain hunters will stack up a lot of namecoins and let the auto_renew do their job for years.

**Comment by n074v41l4bl34u** [comment]
The price of NMC in terms of USD is falling precisely because it is still hard to manage NMC assets - lack of auto-renewal is a factor. No sane person is going to manually renew thousands of domains, identities or whatever asset class will be included in the NMC blockchain in the future.
Automatic renewal is essential for efficient asset management and if core client does not support it some other client/tool definitely will but the price will suffer as a result.
