### ISSUE TITLE
Namecoin 0.3.80 not syncing via proxy on winXP

### ISSUE THREAD

**Issue by sanyanet2** [namecoin/namecoin-legacy#237]
The client just start listening TCP 8334 and thats it. 
Though it should use sock5 proxy from the network settings and sync with the network like bitcoin core.

**Comment by JeremyRand** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

sanyanet2:
> The client just start listening TCP 8334 and thats it. Though it
> should use sock5 proxy from the network settings and sync with the
> network like bitcoin core.

Any chance you could try Namecoin Core 0.13.99-name-tab-beta1?  I
think it's likely that this issue was fixed between 0.3.80 and that
release.  Downloads are available at
https://namecoin.org/download/betas/ .

-----BEGIN PGP SIGNATURE-----

iQIcBAEBCgAGBQJYYSJfAAoJELPy0WV4bWVw2XoQAMXgoT11nSSQmquUhZLQgHqQ
RCs7b3CsH7LhHJQbmX7J4QHcyKQGXJi+l6cYUTtJ92F4uE4yh3S0FL8sw7SP50+c
8G4XxMAdB97u5vuQk9XI+prVi80ISD/dhkB4TVS9Y6E8a0p5pqnIUlKOGz4WWW7O
sISPbyXm8ycsPuESfnKSzCXo5O85RQATvWv6e1eggbHfEPTGqt7uKovs+vhK086n
/Gy6pE1ReIxAJW2da6B+xaDp+/YXcyB/0bIISptsjUlzGV0AnMpYMNrGL6TeGPl5
TDAB8J6aKJZd2P3Z45Dv7TZNp+MWarfpEljzOY9KOWu9s+fL88oSl5UTjsH61CGJ
lt/lkchfsz/krWsgxwz0epyCocxAs/n5VMth8mJNa20J4tOjWYA7gGwXLCslrKWX
a4IeNFzAoo/9bc22ifVcuPq2Mp9p3VMgQwsCH3I9a31O1WnAcUuxsW8cZzTkMj9N
bNj8OiZ5zmLsE8a5u+ApBZLX6r5+CqmFwwU5ULiXYPOr18FNgZtX1OKdjEzVmIK0
mOcNVQlWTOVr1PjrzPn4MuFHWzyzUBi5SZDPmxYTuT9I7iHuxJGgYFjkcbbphY73
sj8gzhCFMxty64KnbHHyUnRZj1OQSKHZs0qfqgTZnULQzTvBsDfSYD9qgON2WnlT
mi9oSdV+hVLLw2HLVDi3
=q94+
-----END PGP SIGNATURE-----

**Comment by sanyanet2** [comment]
in this version of a client 
Namecoin Core 0.13.99-name-tab-beta1

there are two configurations for proxy neither of that is working
if I disable option "allow incoming connections" then client shows no network activity at all.

if I set only tor proxy then sometimes it listen on the UDP port  63862

**Comment by JeremyRand** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

sanyanet2:
> in this version of a client Namecoin Core 0.13.99-name-tab-beta1
> 
> there are two configurations for proxy neither of that is working 
> if I disable option allow incoming connections then client shows no
> network activity at all.

Can you open an issue in the namecoin-core repo about this?  Also
please make sure that the issue doesn't occur in upstream Bitcoin Core.

-----BEGIN PGP SIGNATURE-----

iQIcBAEBCgAGBQJYYU6iAAoJELPy0WV4bWVwjsUQAItQwW763ORiQ0Zw4AP+5MI4
LgZo+qH+JocTH/lwQ6fogqTOyqqYqfIepzQhXfBd4morCLBIqOrPkaXubrf8UTCx
+LhTQpm+HcK4MUlYG4gmtIT053SurgGPwZCY4aChAWieHDw4VQK8Mk798z620BLN
KG3VZ2G45oBcsBEA2rOTVrLkDVk+O6tLKmxrezRLAJbR9r0TZfqluKM4pz4H6piI
tp6VTm+sqQYzw2+SdDzNML+Er74z0slgSTxAqXrppFEGZmA1K2kcFg4C/ADj8d7B
aUI34mkyI2xT1cSyjEH0vQoI85PeyLT9p651ULVTkx5vwQrUFNmQlyNZY+FPuYLs
5pZVJEiKX/F0Sqg/qXI48Mxu4CH2uGxVjhq/KVJgJvWWPKW3xIVUliEGVE1yuap4
c6Q/MezhVwEFeSUpNXov0CQUc6nbz0RCirbNA05pKDfxS3dECPs3UU+frgs5SeAs
LkeDGPAignidlgZjX/rV7urua1bmJCxbl+6AULV4bp3AFQ++qUiRIok3zOKdsJDC
9BlNHXPg526lZxIPFQS0cn+OffT3cINQxCqQXh9jYwmSU6MD5Yb+c3Lt035JsyCc
fbKibtUJh3fJM6zbAIGWCZjFKEO+jD8zlvz69HVCBujkHpvKvyoWair62CsRGWKl
60T7EowcUyX/Vko1RoYo
=5kJ6
-----END PGP SIGNATURE-----

**Comment by sanyanet2** [comment]
hm, actually same issue with original bitcoin core of version 13.

**Comment by JeremyRand** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

sanyanet2:
> hm, actually same issue with original bitcoin core of version 13.

Well, then I don't think there's anything we can do about it.  Sorry.
 :(  If it's not fixed in latest master branch of upstream Bitcoin
Core, feel free to file a bug there (if you're certain that it's not a
problem on your end).

Cheers.
-----BEGIN PGP SIGNATURE-----

iQIcBAEBCgAGBQJYYZvxAAoJELPy0WV4bWVwvWUP/jIovep8lRbd95K5lZtcJPQR
HlczkypXfPoiqkAMAzZjV/g/+Bm3pP6aGGlUEgCFafOhNMeB7VWAE/IvYhHlYePy
UAUy47cOIrxs4Vaga/xTD4Ee0Nl6wI3KfGjiISWVvglNuMMjgaX652HgQQU+BGg0
H8pUTYxhStc3r7f0ddW+O1rZ2qKI/DoWhrNiqIdL5V/XIz4g4Ea3gZP8zOR+QIiO
1VqD5dCSs3ydMYLhJKB4wB6hRXtdxaINXVketuQ/ZDGTVg+AkeCpr5Vl1ewiSFXi
2atoMpWbgjgwULXRwvKH0woYxo8WRC541AhvE/aoPKplWsAdubeoXpKOt9KGwj2e
Bxy/Zn3MZmjmYmB2Q1bOlrakEjHbCe/aSENWLnpagVAl3NMp7iL55C0mwh9jy33G
pD6Pd6I3Z+6Ac9VuEtS2hx4tQpt4WW8F+NPYPWosCmOLGTezUoP9407+TUI6EvPm
6IbVxcnDEwVaBGbZHIJZBB/TVRqiI0CWrU/BUBmCXhovjX486J+B7cfzHydHBE2F
0GgBZNWrcmiGfdWwzogqwQu7iGIFUVL79oSTZ9KA/JnpPQPePCwA9JV++TRVYZdE
NkxSxMiUlW0myecGZG5Q0MWvKs5XlnsVm5Rw/8aw+GfmIeEa7BkqWOqJJUhC4t3r
4cwB3Z8tQqLhOsiQBPMb
=ZwmC
-----END PGP SIGNATURE-----
