### ISSUE TITLE
RFE integrated .bit dns server

### ISSUE THREAD

**Issue by SkillfulHacking** [namecoin/namecoin-legacy#32]
The client needs to have the ability to enable a .bit dns server by enabling a feature, either in a config file or a command line/rpc request.

**Comment by Pagel1928** [comment]
Actually, namecoin is not supposed to be solely a domain name system, it is data agnostic. Several different systems actually can be built ontop of namecoin, right now the domain name system and the identity system are the most mature. Thats why a DNS server should be a third party application that communicates with namecoind, rather than built in directly.
