### ISSUE TITLE
Back/port Bitcoin Test-net Difficulty Reset

### ISSUE THREAD

**Issue by indolering** [namecoin/namecoin-legacy#43]
- [x] [Bitcoin commit for difficulty adjustment](https://github.com/bitcoin/bitcoin/commit/c52296a73e5222628bf6a03eaf727622594bf464).
- [ ] [New genesis block (ex on commit)](https://github.com/bitcoin/bitcoin/commit/98ba262a48b66cae8478525e809898512e997948).
- [ ] [Change the chain ID (ex on commit)](https://github.com/bitcoin/bitcoin/commit/a9d811a9760720d29eb1be3b738e59a1621cc6d6) ("but it is optional" -not entirely sure what that means).

Wants
- [ ] Slick wiki page on how to join test-net
- [ ] An auto-updating stock VM or install script would be greatly appreciated.

**Comment by khalahan** [comment]
I've made 2 pull requests (one for each branch https://github.com/namecoin/namecoin/pull/53, https://github.com/namecoin/namecoin/pull/54) to allow difficulty adjustment on current testnet.

I planned a testnet hard fork on 15/03/2014 (not a lot of users will be affected, so, I think this date is OK).

Please, review this code soon so we could do tests on testnet again :p

**Comment by indolering** [comment]
This is GREAT timing!

**Comment by khalahan** [comment]
I've tested the patch with a past date and successfully generated the next block in some seconds (you can see it on the block explorer : [34715](http://testnet.explorer.namecoin.info/b/00000e5c7ffbed92faf47b431dbd9fb5b02374b4b430ce078dcd7e396330151b). As it has a time before 15 Mar, it is only valid for my modified node).

The block 34716 didn't generate in some seconds, as expected.

**Comment by dthorpe** [comment]
Hurray!  What's the recommended process to test?  Just pull the branch code, build and run in namecoind -testnet?

**Comment by dthorpe** [comment]
The new code has successfully broken the Feb 14 logjam on namecoin-testnet. However, the current difficulty still seems to be rather high. If the namecoin (testnet) block chain is supposed to have a target of one new block every 10 minutes, then we're still pretty far off of that goal.

Observed behavior with the latest difficulty adjustment fixes:  If no new blocks have been generated in the past 20 minutes, then starting namecoind --testnet --gen=1 will generate a new block almost immediately (within 3 minutes, typically). After that initial block, though, it may be hours before the next block is generated.  I can "force" a new block by stopping the hash generator (setgenerate false) and restarting the hash generator (setgenerate true). If I do this more than 20 minutes after the last block appeared on the blockchain, then it will spit out a new block almost immediately. Lather 20 minutes, Rinse, Repeat.

I have a 2nd machine running the same 0.3.73 build of namecoin on testnet that I leave running 24/7.  It generates a new block roughly every 4 hours overnight.

Is the difficulty adjustment supposed to reduce difficulty until the network-wide block generation rate approaches the 10 minute goal?  If so, it doesn't seem to be doing that.  The difficulty adjustment only seems to apply when first starting the hash generator.

p.s. The rate of new blocks shown in http://testnet.explorer.namecoin.info/ is artificially elevated because I've been "forcing" new blocks every 20 minutes or so throughout the day to get enough confirmations through so I can get on with my product development experiments using namecoin testnet.  120 confirmations at 4 to 6 hours each means the testnet coins I mined last week won't be available for at least a month!

**Comment by khalahan** [comment]
The patch is supposed to allow a new block after 20mn, with the min difficulty.
.
From what you say, the rpc command "setgenerate true" (same as the command line option, but easier to enable/disable) doesn't seem to get the right difficulty after the first block... A minor bug which would require a new issue I guess.

If you do "setgenerate true" / [block generated] / "setgenerate false" / [wait 20mn] / "setgenerate true", you should have a second block.
