### ISSUE TITLE
Custom wallet filename option

### ISSUE THREAD

**Issue by phelixbtc** [namecoin/namecoin-legacy#78]
I think a custom wallet filename option would be helpful.

Could probably be based on this:
https://github.com/old-c-coder/bitcoin-git/commit/929019012dc7d93fd3ba59d8eb553e390211a713

**Comment by domob1812** [comment]
Sounds like a useful thing to have.  I'll put that on my list for later.

**Comment by domob1812** [comment]
Another idea:  Even better would be a way to switch out wallets for a running daemon.  For instance, with a new RPC command.  Not sure how invasive this would be, but it is probably possible.  (Need to flush the old wallet, close the db handle, and re-open.)

**Comment by phelixbtc** [comment]
Yeah, that would be better. I wonder whether there is already one of the altcoins that has this implemented...

**Comment by CodeChief** [comment]
The config file is called namecoin.conf not bitcoin.conf. Or do we have seveal forks here some with the old mistake? The current code I got from namecoin/namecoin has the correct unique namecoin.conf, but I've seen some posts with people getting confused or having to rename their namecoin.conf to bitcoin.conf to get their builds working.

To follow the same pattern as all other alt coins, the name of the config file should match the network/coin name. Another similar mistake was the use of 8332 for the RPC port and 18332 for the test RPC port. In current source they were corrected to 8336 and 18336 (no longer clashing with BitcoinD).

I've recently had a pull request accepted in P2Pool to correct these, so please make sure any new pull/merge requests do not regress the current namecoin config file and RPC port fixes. This sort of thing should go into the README to inform people, not to continue making the same mistake. Not sure about the long term history of this, perhaps one of the original developers can clarify?

**Comment by domob1812** [comment]
Not sure whether it is related to this PR or not, but:  namecoin.conf is the correct config file, as well as the ports you mention.  Why do you bring this up?  There are no plans to change this, as far as I know.  I think that bitcoin.conf works, too, and is tried as fallback (and was used in the past).

**Comment by CodeChief** [comment]
Oh it looks like my post landed on the feature request not the merge request from @digital-dreamer, to quote "You can set walletpath=(file) in bitcoin.conf to use a custom wallet file".

Was just a reminder in case somebody was checking-in some new code on the basis of old standards. Anyway @domob1812 thanks for clarifying it sounds okay if namecoin is already falling-back to cover legacy setups/people who don't know it's fixed. Because I found some quite popular tutorials still using the old name and ports, I think this should be underlined as a friendly reminder each time people continue to use the legacy values. The README file would make sense as a start and check all wiki pages too.

**Comment by phelixbtc** [comment]
Solved as of https://github.com/namecoin/namecoin/pull/121
